### ISSUE TITLE
Dataset's Zip File is Damaged/ Corrupted

### ISSUE THREAD

**Issue by tzpranto** [florianst/picrispr#1]
![image](https://user-images.githubusercontent.com/19242822/217720625-25540b90-dc94-40c7-b3d4-9893f01409ba.png)

**Comment by florianst** [comment]
Thank you for your comment! The dataset was compressed using pandas and can be opened using
`dataset = pd.read_csv('offtarget_260520_nuc.csv.zip')`. You can then export a csv file from this using `dataset.to_csv()`. I've adjusted the readme file to make this clearer.
